development:
  strategy: oauth
  oauth_consumer_key: fsPsemKGezFYbXI1jYbEKg 
  oauth_consumer_secret: aC5xPz5mdDJtb8Yp1XroTBpYauXOigHi7UBM5g2byEg
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: testkey
  oauth_consumer_secret: testsecret
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: fsPsemKGezFYbXI1jYbEKg
  oauth_consumer_secret: aC5xPz5mdDJtb8Yp1XroTBpYauXOigHi7UBM5g2byEg 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days

